### PR TITLE
Add option for domain specific target_domain

### PR DESCRIPTION
**Pull request by mbjurstrom**
This should implement the requested feature in https://github.com/tiredofit/docker-traefik-cloudflare-companion/issues/28

And also will solve the problem mentioned in https://github.com/tiredofit/docker-traefik-cloudflare-companion/issues/7#issuecomment-695751017. So it won't attempt to create a cname for the main domain.

### CODE REVIEW

**Comment by tiredofit** [comment]
Thanks for this. Looking at this though, will it break the ability to have people simply rely on "TARGET_DOMAIN" ?

Perhaps you can work something in so that if there is no TARGET_DOMAIN(x) that it defaults to the main defined TARGET_DOMAIN

**Comment by mbjurstrom** [comment]
> Thanks for this. Looking at this though, will it break the ability to have people simply rely on "TARGET_DOMAIN" ?
> 
> Perhaps you can work something in so that if there is no TARGET_DOMAIN(x) that it defaults to the main defined TARGET_DOMAIN
The line below should already handle that case.
`'target_domain': os.environ.get("{}_TARGET_DOMAIN".format(k), target_domain),`

**Comment by tiredofit** [comment]
Great. I will test in the next day

**Comment by tiredofit** [comment]
Tried to test it with the existing container, and I have a variable population check looking for `TARGET_DOMAIN` which will need to be removed, or at least check to see existence of a TARGET_DOMAIN*. You can test this by commenting out line 8 in `installl/etc/cont-init.d/10-cloudflare-companion`

However, when I test this PR on my system, it still throws an error via the Python script with: `ERROR: 'TARGET_DOMAIN' not defined` and exiting.

My test involved simply stopping to use `TARGET_DOMAIN1` instead of `TARGET_DOMAIN`.

**Comment by mbjurstrom** [comment]
> Tried to test it with the existing container, and I have a variable population check looking for `TARGET_DOMAIN` which will need to be removed, or at least check to see existence of a TARGET_DOMAIN*. You can test this by commenting out line 8 in `installl/etc/cont-init.d/10-cloudflare-companion`
> 
> However, when I test this PR on my system, it still throws an error via the Python script with: `ERROR: 'TARGET_DOMAIN' not defined` and exiting.
> 
> My test involved simply stopping to use `TARGET_DOMAIN1` instead of `TARGET_DOMAIN`.

The syntax I added that it check for are DOMAIN1_TARGET_DOMAIN, DOMAIN2_TARGET_DOMAIN and so on. 
I still expected the user to supply a default/fallback target_domain in the TARGET_DOMAIN variable.  Cause you might not want to define a specific target_domain for each of your domains maybe just a few and have the other reuse the default one. 

Even though it would look better to rename it to DEFAULT_TARGET_DOMAIN instead. But that would be a breaking change for existing users. While I opted to keep it as TARGET_DOMAIN to allow current user to keep their config working.

**Comment by qnorsten** [comment]
Either you can solve it with the cli. 
Or I will fix it on my side in about 30 minutes

**Comment by mbjurstrom** [comment]
I fixed the conflict:)

**Pull request merged**
