### PR TITLE
No Cloudflare entries possible due to change in API

### LINKED ISSUE #103: No Cloudflare entries possible due to change in API
### Summary
Cloudflare changed the API so that the ttl value has to be a number. This throws the following error when cloudflare companion tries to create a new dns entry:
`...+0200 ERROR | ** service.example.com - 9022 TTL must be a number, not a string.`

### Steps to reproduce

- Let Cloudflare Companion try to create a new dns entry

### What is the expected *correct* behavior?

Cloudflare companion sends a successful API request and a new DNS entry gets created

### Environment

- Image version / tag:  latest
- Host OS: debian 12
    
### Possible fixes
Change the ttl value to a number in the API request

### PR DESCRIPTION
**Pull request by appiekap653**
Fixes #103

### CODE REVIEW

**Review by appiekap653 — COMMENTED** [review]
tested it and makes it work again

**Review by tiredofit — APPROVED** [review]
Thanks!

**Comment by ppokrovsky** [comment]
Thank you!

**Comment by StefanArts** [comment]
Thanks a lot!

**Pull request merged**
