### PR TITLE
Add cloudflare API token support

### PR DESCRIPTION
**Pull request by blinkiz**
This patch makes it possible to use Cloudflare new API Tokens feature. This makes the Cloudflare account safer by not requiring administrator permissions given with the Global API Key.

### CODE REVIEW

**Comment by tiredofit** [comment]
This is great stuff.
With this change, will it limit the ability to use an email and global token? I am just concerned that this will introduce some breaking changes for people who are relying on the old environment variables.

I can certainly build something in to warn people to start making the shift to the new variables, while still letting the old ones work if they do.

**Comment by blinkiz** [comment]
Yeah you are right, I did not thought about that.
Well..
If CF_EMAIL is set and CF_API_EMAIL is unset, set CF_API_EMAIL == CF_EMAIL.
If CF_TOKEN is set and CF_API_KEY, set CF_API_KEY == CF_TOKEN.
That should probably be put in the built python file. I would like to get rid of the EOF building of the python file in the future so please do not expand that :slightly_smiling_face:

**Comment by tiredofit** [comment]
Running in Pure Python would be ideal, agreed. I'm a self proclaimed hack with Python for some reason which is why I did things they way I did. Someone a while back submitted a PR in pure python for the [brother image of this](https://github.com/tiredofit/docker-nginx-proxy-cloudflare-companion/pull/2) however I haven't had the time to sit down and analyze just what exactly I could do to convert this image over in the same way.

I'm certainly happy to take a PR if you are willing to take it on as I'll be a few weeks away from when I'll be able to carve off a couple solid hours to dedicate to this.

**Comment by blinkiz** [comment]
Yeah true that. Am no python coder myself but I can probably get something together.

**Comment by htpcBeginner** [comment]
Any progress on this PR? This would be great to have.

**Comment by tiredofit** [comment]
@blinkiz Thank you for your initial work on this. I closed the PR after trying to merge yet there were too many conflicts in getting it into the current tree. I've credited you in the Changelog for the initial work - It's now live!

**Comment by blinkiz** [comment]
Nice. Thank you for a great product that was missing in my work flow.

**Pull request closed without merging**
